# Sample data generated by ChatGPT. Data source can be modified in the future.
def get_sample_documents():
    data = [
        {
            "content": "Domain suspension occurs when WHOIS information is incomplete, inaccurate, or when domains are used for spam, malware, or other policy violations. Suspended domains must have WHOIS details updated within 30 days or face permanent suspension.",
            "source": "Domain Suspension Policy",
            "category": "abuse_compliance",
            "section": "4.2",
            "priority": "high",
            "action_type": "escalate_to_abuse_team"
        },
        {
            "content": "A domain found distributing phishing content must be immediately locked and escalated to the abuse team. Include all reported URLs and customer history with the escalation.",
            "source": "Abuse Handling Playbook",
            "category": "abuse_compliance",
            "section": "5.2",
            "priority": "critical",
            "action_type": "escalate_to_abuse_team"
        },
        {
            "content": "If repeated complaints of outbound spam are confirmed against a hosted email service, suspend the account temporarily and escalate the issue to the abuse team with full mail logs.",
            "source": "Email Acceptable Use Policy",
            "category": "abuse_compliance",
            "section": "3.4",
            "priority": "high",
            "action_type": "escalate_to_abuse_team"
        },
        {
            "content": "If malware hosting is detected on customer servers, capture affected file hashes and escalate immediately to the abuse team for further remediation.",
            "source": "Security Response Guidelines",
            "category": "security",
            "section": "2.1",
            "priority": "critical",
            "action_type": "escalate_to_abuse_team"
        },
        {
            "content": "When a customer disputes a renewal charge after the grace period, escalate the case to the billing team for potential refund or adjustment approval.",
            "source": "Billing and Refund Policy",
            "category": "billing",
            "section": "4.3",
            "priority": "medium",
            "action_type": "escalate_to_billing_team"
        },
        {
            "content": "If an automatic payment retry fails three times, escalate to the billing team to investigate possible fraud blocks or card restrictions.",
            "source": "Payment Processing Guide",
            "category": "billing",
            "section": "2.2",
            "priority": "high",
            "action_type": "escalate_to_billing_team"
        },
        {
            "content": "In cases where chargebacks are reported by the bank, immediately escalate to the billing team with transaction IDs and customer communication logs.",
            "source": "Chargeback Handling SOP",
            "category": "billing",
            "section": "5.1",
            "priority": "critical",
            "action_type": "escalate_to_billing_team"
        },
        {
            "content": "If a takedown request citing trademark infringement is received, escalate to the legal team with a copy of the complaint and all related customer data.",
            "source": "Trademark Dispute Handling Guidelines",
            "category": "legal",
            "section": "6.1",
            "priority": "critical",
            "action_type": "escalate_to_legal_team"
        },
        {
            "content": "Subpoenas or law enforcement data requests must be logged and escalated to the legal team without customer notification, per compliance policy.",
            "source": "Law Enforcement Request Policy",
            "category": "legal",
            "section": "8.3",
            "priority": "critical",
            "action_type": "escalate_to_legal_team"
        },
        {
            "content": "If a DMCA takedown notice is filed against hosted content, escalate to the legal team along with timestamps, hosting account ID, and content metadata.",
            "source": "Copyright Infringement Policy",
            "category": "legal",
            "section": "7.2",
            "priority": "high",
            "action_type": "escalate_to_legal_team"
        },
        {
            "content": "If multiple customers report DNS resolution failures traced to our authoritative servers, escalate to the operations team with traceroute and system logs.",
            "source": "Operations Escalation Protocol",
            "category": "infrastructure",
            "section": "9.4",
            "priority": "critical",
            "action_type": "escalate_to_operations_team"
        }
    ]

    return data